name: fmm-galaxy-sim
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - matplotlib
  - pandas
  - pyarrow
  - pytest
  - pyyaml
  - tomli
  - cmake
  - ninja
  - doxygen
  - breathe
  - furo
  - myst-parser
  - sphinx
